image:
  repository: weaveworks/kured
  tag: 1.2.0
  pullPolicy: IfNotPresent
  pullSecrets: []

extraArgs: {}

rbac:
  create: true

podSecurityPolicy:
  create: false

serviceAccount:
  create: true
  name:

autolock:
  enabled: true
  image:
    repository: docker.io/bitnami/kubectl
    tag: 1.15.4
  scheduleUnlock: 13 10 * * *
  schedulelock: 14 10 * * *

updateStrategy: OnDelete


tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule

priorityClassName: ""

nodeSelector: {}

podAnnotations: {}

